name: Deploy to Firebase Function via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools@latest

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT }}" > "$HOME"/firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/firebase_key.json
          
      - name: Deploy Function
        if: ${{ env.CI == 'true' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          run: npx firebase-tools deploy --only functions:offers --project petszone-arg

