name: Deploy to Firebase Function via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Debug Secret
        run: |
         echo "${{ secrets.SERVICE_ACCOUNT }}" > "$HOME"/firebase_key_debug.json
         cat "$HOME"/firebase_key_debug.json

      - name: Authenticate with Firebase
        run: |
         echo "${{ secrets.SERVICE_ACCOUNT }}" > "$HOME"/firebase_key.json
         export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/firebase_key.json
         echo "GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_APPLICATION_CREDENTIALS"
         firebase use --add petszone-arg

      - name: Download deps
        working-directory: src
        run: npm install

      - name: Deploy Function
        if: ${{ env.CI == 'true' }}
        run: npx firebase-tools deploy --only functions:offers --project petszone-arg
