name: Deploy Cloud Function
on:
  push:
    branches: [ main ]
env:
  PROJECT: mkdevyoutube

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@latest
        with:
          project_id: ${{env.PROJECT_ID}}
          service_account_key: ${{ secrets.PRIVATE_KEY_ID }}
          export_default_credentials: true

      - name: deploy cloud function
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: ${{ env.FUNCTION_NAME }}
          runtime: nodejs16
          project_id: ${{env.PROJECT_ID}}
          entry_point: ${{ env.FUNCTION_NAME }}
