name: Deploy to Firebase Functions via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT_KEY" > "$HOME"/firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/firebase_key.json

      - name: Download deps
        working-directory: src
        run: npm install

      - name: Deploy
        run: npx firebase-tools deploy --project <your-firebase-project-id>
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
