name: Deploy to Google Cloud Function via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Cloud Function
        id: deploy-function
        uses: google-github-actions/deploy-cloud-functions@v1.0.1
        with:
          name: offers
          runtime: nodejs16
          project: petszone-arg
          credentials: firebase-adminsdk-ehh6v@petszone-arg.iam.gserviceaccount.com
