name: Deploy to Firebase Functions via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo "${{ secrets.SERVICE_ACCOUNT }}" > "$HOME"/firebase_key.json
          export GOOGLE_APPLICATION_CREDENTIALS="$HOME"/firebase_key.json

      - name: Download deps
        working-directory: src
        run: npm install

      - name: Deploy
        run: npx firebase-tools deploy --only functions:offers --project petszone-arg --token ${{ secrets.FIREBASE_TOKEN }}
